markdown: kramdown
title: Hands-on Exercises
exclude: [README.md, where-to-go-from-here.md, less]
organizers-email: "ampcamp@cs.berkeley.edu"
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: ''
